test: VolumeHealthMonitoring
Signed-off-by: Jakob Möller <jmoller@redhat.com>

diff --git a/test/e2e/Makefile b/test/e2e/Makefile
--- a/test/e2e/Makefile
+++ b/test/e2e/Makefile
@@ -241,12 +241,27 @@ common/create-vg:
 	$(SUDO) vgcreate -y node$(ID)-thin1 $$($(SUDO) losetup -j $(BACKING_STORE)/backing_store$(ID)_7 | cut -d: -f1)
 	$(SUDO) lvcreate -T -n pool0 -L 4G node$(ID)-thin1
 
+	# Create Volume Group for Volume Health Monitoring Failure Check
+	truncate --size=2G $(BACKING_STORE)/backing_store$(ID)_8
+	truncate --size=2G $(BACKING_STORE)/backing_store$(ID)_9
+
+	# Setup loop devices
+	$(SUDO) losetup -f $(BACKING_STORE)/backing_store$(ID)_8; \
+	$(SUDO) losetup -f $(BACKING_STORE)/backing_store$(ID)_9; \
+	echo test | $(SUDO) cryptsetup open --type plain \
+		$$($(SUDO) losetup -j $(BACKING_STORE)/backing_store$(ID)_8 | cut -d: -f1) e0; \
+	$(SUDO) vgcreate -y node$(ID)-volume-health \
+		/dev/mapper/e0 \
+		$$($(SUDO) losetup -j $(BACKING_STORE)/backing_store$(ID)_9 | cut -d: -f1)
+
 .PHONY: common/remove-vg
 common/remove-vg:
 	for name in thick1 thick2 raid1-1 raid1-2 thin1; do \
 		$(SUDO) vgremove -ffy node$(ID)-$${name}; \
 	done; \
-	for i in $$(seq 7); do \
+	$(SUDO) vgremove -ffy node$(ID)-volume-health
+	$(SUDO) dmsetup remove -f /dev/mapper/e0 || true
+	for i in $$(seq 9); do \
 		$(SUDO) pvremove -ffy $$($(SUDO) losetup -j $(BACKING_STORE)/backing_store$(ID)_$${i} | cut -d: -f1); \
 		$(SUDO) losetup -d $$($(SUDO) losetup -j $(BACKING_STORE)/backing_store$(ID)_$${i} | cut -d: -f1); \
 		rm -f $(BACKING_STORE)/backing_store$(ID)_$${i}; \
